### ISSUE TITLE
Установка библиотеки

### ISSUE THREAD

**Issue by alexandrettto** [cia76/FinamPy#10]
Добрый день! Подскажите, пожалуйста, как можно установить вашу библиотеку? 

Я использую команду: !pip install git+https://github.com/cia76/FinamPy.git#egg=FinamPy
Но получаю ошибку: ERROR: FinamPy from git+https://github.com/cia76/FinamPy.git#egg=FinamPy does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by cia76** [comment]
Александр, добрый день!

Просто забирайте архив через git clone. Я обязательно опубликую свои проекты на pip когда брокеры стабилизируют свои API.
