### ISSUE TITLE
Ошибка BAD_REQUEST Invalid Security Board

### ISSUE THREAD

**Issue by alexandrettto** [cia76/FinamPy#11]
Добрый день! Столкнулся с проблемой, что подписка на стакан для бумаги: RU000A106YN4 и BOARDID: TQIR выдает ошибку: 
<img width="976" alt="Снимок экрана 2024-04-26 в 16 55 33" src="https://github.com/cia76/FinamPy/assets/62796125/681b5505-a1e6-4c4a-b775-3f55f866fc33">

Это как-то можно исправить? Или это фича сервера, что он не знает про такой BOARDID?

**Comment by cia76** [comment]
Александр, это ошибка сервера Финам. Тикер в их наборе инструментов имеется:

      "code": "RU000A106YN4",
      "board": "TQIR",
      "market": "MARKET_STOCK",
      "decimals": 2,
      "lotSize": 1,
      "minStep": 1,
      "currency": "RUR",
      "shortName": "GrupPro1P3",
      "properties": 199,
      "timeZoneName": "Russian Standard Time",
      "bpCost": 10.000000000000002,
      "accruedInterest": 12.71,
      "priceSign": "PRICE_SIGN_POSITIVE",
      "lotDivider": 1

Площадка определяется у тикера верно. Когда ставим подписку на стакан, то получаем:

request_id: "orderbook1"
errors {
  code: "BAD_REQUEST"
  message: "Invalid Security Board"
}

Отпишусь разработчикам Финама. Пусть смотрят.

**Comment by alexandrettto** [comment]
Спасибо! Я тоже это обнаружил и забыл закрыть это issues. 
Я написал им о проблеме (https://github.com/FinamWeb/trade-api-docs/discussions/54). Вы коммуницируете с ними по этому каналу?
