### ISSUE TITLE
Время выгрузки стаканов

### ISSUE THREAD

**Issue by alexandrettto** [cia76/FinamPy#12]
Добрый день! У меня вопрос касательно время выгрузки стаканов. В среднем на 200 бумаг (облигаций) это занимает примерно 5 минут (см. распределение по времени выгрузки). В то же время, если пользоваться tinkoff-api, то там на загрузку 600 стаканов уходит примерно 1 минута.

 
Как-то можно ускорить выгрузку стаканов в finam-api? 
В чем может быть отличие данных сервисов, если оба используют gRPC протоколы?

<img width="628" alt="Снимок экрана 2024-05-03 в 15 47 09" src="https://github.com/cia76/FinamPy/assets/62796125/7ec4ca39-7d28-47c2-b316-aaf9cb7695b0">

**Comment by cia76** [comment]
Александр, добрый день!

gRPC - это просто технология (стандарт). Она не несет в себе обязательства быть производительной. Я не являюсь сотрудником Финама или Тинькофф Инвестиции, поэтому мой ответ воспринимайте как возможные причины (мысли вслух).

- Каждый брокер пишет API под свою инфраструктуру. Финам пишет под TRANSAQ. Если в TRANSAQ есть "узкие места", то они переходят и в API

- Тинькофф вывел API в промышленную эксплуатацию летом 2023 года. У Финама до сих пор идет разработка. Обычно при разработке не используются все возможные мощности.

- Можно уменьшить время отклика работая асинхронно. Сделали запрос. Не ждем ответа, запускаем следующий запрос. Когда начинают приходить ответы, собираем их. Также распределить нагрузку запросов можно по нескольким одновременным подключениям. С этой техникой нужно быть осторожнее, т.к. и у Тинькофф и у Финама есть ограничения на кол-во запросов в минуту и кол-во одновременных подписок.
