### ISSUE TITLE
Зависимость googleapis-common-protos несовместима с protobuf 5.26.1

### ISSUE THREAD

**Issue by ag95v2** [cia76/FinamPy#13]
Добрый день! Не удалось сходу запустить ваши примеры.
При попытке установить зависимости при помощи команды:
`pip install -r requirements.txt`

Возникает предупреждение:

> ERROR: googleapis-common-protos 1.63.0 has requirement protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5, but you'll have protobuf 5.26.1 which is incompatible.
> Installing collected packages: grpcio, protobuf, types-protobuf, googleapis-common-protos
> Successfully installed googleapis-common-protos-1.63.0 grpcio-1.63.0 protobuf-5.26.1 types-protobuf-5.26.0.20240422
> 

В дальнейшем, если его игнорировать, возникает проблема на этапе импорта файла protobuf/internal/builder.py внутри сгенерированных файлов в директории proto и код не запускается.

**Comment by cia76** [comment]
На "чистых" компьютерах под Windows и Ubuntu поставил пакеты через `pip install -r requirements.txt`

Установленные библиотеки полностью совпали с Вашим вариантом:
googleapis-common-protos-1.63.0
grpcio-1.63.0
protobuf-5.26.1
types-protobuf-5.26.0.20240422

Везде примеры запустились без ошибок.

Вы получили ошибку, что protobuf 5.26.1 не совместим с googleapis-common-protos 1.63.0. Нас просто уведомляют, что библиотеки не совместимы. Ничего поделать с этим не можем.

Попробуйте запустить Connect.py Отпишите сюда ошибку. Возможно, из нее что-то будет понятнее.

**Comment by ag95v2** [comment]
К счастью, уже не могу воспроизвести состояние, в котором были ошибки.
В полностью свежем виртуальном окружении всё работает, спасибо!
