### ISSUE TITLE
Накопление необработанных обновлений стакана

### ISSUE THREAD

**Issue by ag95v2** [cia76/FinamPy#15]
Добрый день!
Недавно я столкнулся с одной особенностью поведения подписки на стаканы: обычно обновления приходят примерно раз в секунду, но иногда возникает пауза от нескольких секунд до нескольких десятков секунд, после которой приходит сразу много обновлений. Число пришедших после паузы обновлений примерно равно длительности паузы в секундах, что наводит на мысль о том, что события где-то буфферизуются, а потом разом "выплёвываются".
Предположение о том, что во время паузы на биржу просто не поступали заявки не кажется правдоподобным, поскольку пауза возникает одновременно с точностью до секунды в нескольких стаканах ликвидных инструментов и длится одно и то же время.
Подозрения на сеть тоже отпадают: паузы возникают одновременно локально и в облаке (ваша библиотека по этой же причине не вызывает подозрений).

Хотел бы узнать, что вы думаете по этому поводу:

-  Сталкивались-ли с этой проблемой?
-  Возможные причины наблюдаемого поведения?
-  Есть-ли какие-то (хотя бы неформальные) обещания со стороны брокера о том, с какой частотой он (хотя бы пытается) высылать обновления стакана пользователю?
-  Как лучше всего повысить надёжность получения свежего стакана? Может быть, сбрасывать и обновлять подписку, или есть возможность снабдить стакан информацией о том, на какой момент он был актуален (в рамках вашей библиотеки или самого api)?

**Comment by cia76** [comment]
Добрый день! По данным Финама, сейчас ведется разработка с правкой "боевого" кода API. Как будут новости от Финама, что спринт разработки завершен, тогда проверим. Локальные сбои в Финаме случаются. Все, что можно сделать с моей стороны, вношу в код FinamPy.

**Comment by ag95v2** [comment]
Спасибо! С нетерпением буду ждать ваших успехов!
