### ISSUE TITLE
Пример использования keep_alive

### ISSUE THREAD

**Issue by publine2** [cia76/FinamPy#5]
Можете показать пример использования keep_alive?

У меня вот такой результат:

fp_provider = FinamPy(Config.AccessToken)
def obrabotchik_keepalive(event):
                       print(event)
fp_provider.on_response = obrabotchik_keepalive
keepAlive_id = uuid4().hex[:16].upper()
res=fp_provider.keep_alive(keepAlive_id)

Получаем вот такую ошибку:

>>> res=fp_provider.keep_alive(keepAlive_id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nocsm/Documents/StocksNocsm/FinamPy/FinamPy.py", line 325, in keep_alive
    request = SubscriptionRequest(order_book_unsubscribe_request=KeepAliveRequest(request_id=request_id))
TypeError: Parameter to MergeFrom() must be instance of same class: expected <class 'proto.tradeapi.v1.events_pb2.OrderBookUnsubscribeRequest'> got <class 'proto.tradeapi.v1.events_pb2.KeepAliveRequest'>.

**Comment by publine2** [comment]
Также у Вас в коде  есть событие on_portfolio, хотелось бы узнать как подписаться на это событие.

**Comment by cia76** [comment]
> Можете показать пример использования keep_alive?
> 
> У меня вот такой результат:
> 
> fp_provider = FinamPy(Config.AccessToken) def obrabotchik_keepalive(event): print(event) fp_provider.on_response = obrabotchik_keepalive keepAlive_id = uuid4().hex[:16].upper() res=fp_provider.keep_alive(keepAlive_id)
> 
> Получаем вот такую ошибку:
> 
> > > > res=fp_provider.keep_alive(keepAlive_id)
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/home/nocsm/Documents/StocksNocsm/FinamPy/FinamPy.py", line 325, in keep_alive
> > > > request = SubscriptionRequest(order_book_unsubscribe_request=KeepAliveRequest(request_id=request_id))
> > > > TypeError: Parameter to MergeFrom() must be instance of same class: expected <class 'proto.tradeapi.v1.events_pb2.OrderBookUnsubscribeRequest'> got <class 'proto.tradeapi.v1.events_pb2.KeepAliveRequest'>.

Добрый день! Да, была ошибка, исправил. Подписка на keep_alive должна выглядеть так:

request = SubscriptionRequest(keep_alive_request=KeepAliveRequest(request_id=request_id))

**Comment by cia76** [comment]
> Также у Вас в коде есть событие on_portfolio, хотелось бы узнать как подписаться на это событие.

Через SubscriptionRequest нельзя подписаться на портфель. Значит, событие изменения состояния портфеля определяется на стороне Финам. Мы его просто принимаем.

**Comment by publine2** [comment]
Я так понимаю, что после подписки на keep_alive - сервер сам по себе ничего не шлет??? т.е. я сам периодически (допустим раз в минуту) должен вызывать функцию fp_provider.keep_alive() чтобы получить ответ от сервера???

по портфелю: если событию on_portfolio назначить свою функцию, то при реальном изменении портфеля ничего нигде не вызывается, т.е. я так понимаю что все это просто не реализовано на сервере финама?

**Comment by cia76** [comment]
> Я так понимаю, что после подписки на keep_alive - сервер сам по себе ничего не шлет??? т.е. я сам периодически (допустим раз в минуту) должен вызывать функцию fp_provider.keep_alive() чтобы получить ответ от сервера???

У Финама keep_alive оформлена как подписка. Мы генерируем у себя request_id, отправляем подписку SubscriptionRequest с типом подписки KeepAliveRequest с request_id. В ответ должно прийти событие ResponseEvent.

Как это работает, объяснено в [документации](https://finamweb.github.io/trade-api-docs/grpc/events#keep-alive)

**Comment by cia76** [comment]
> по портфелю: если событию on_portfolio назначить свою функцию, то при реальном изменении портфеля ничего нигде не вызывается, т.е. я так понимаю что все это просто не реализовано на сервере финама?

В Транзаке много событий передавались "фоном" без оформления подписок. Например, при запуске принудительно на клиента передавались несколько справочников, в т.ч. и спецификация тикеров. API Финама строится на Транзаке.

Догадка такая. Событие было сделано для получения данных в фоне. Но пока его Финам не включил. Как включит, то будем получать. Я, на всякий, в пример 06_Transactions.py включил это событие.

**Comment by cia76** [comment]
Для информации как работает keep_alive. Мы открываем канал связи с Финам. Но сам Финам не знает, мы еще здесь или уже завершили работу. Особенно сложно это определить, если связь принудительно разорвана или мы долгое время (часы или дни) не запрашиваем Финам. Например, в выходные.

Поэтому, Финам со своей стороны разрывает канал. Чтобы этого не произошло, нужно раз в 2-3 минуты (время выбирается экспериментальным путем) посылать запрос keep_alive. В ответ в сервис подписки придет одно подтверждение ResponseEvent. Это означает, что Финам отметил канал как рабочий, и в ближайшее время его удлять со своей стороны не будет.

**Comment by publine2** [comment]
Спасибо за помощь. Хотелось бы еще узнать про keepAlive_id, точнее: каждый новый запрос keep_alive должен выполняться с новым keepAlive_id, или можно один раз получив этот id использовать его во всех последующих запросах пока собственно не разорвется связь.

**Comment by cia76** [comment]
Я для каждого запроса делаю свой id. Когда получаю ответ, то сравниваю, то ли я получил. Технически, мы не ограничены какой id посылать. Можно каждый раз одинаковый.
