### ISSUE TITLE
Котировки

### ISSUE THREAD

**Issue by Shefler** [cia76/FinamPy#6]
Добрый день! Искал, но не нашел примера получения текущей цены. В общем-то также не нашел его в финамовском описании API. Есть какой-то метод получения цены последней сделки? Пусть не по подписке, а обычным запросом. Если это не реализовано в апи, то вопрос насколько оно в принципе поддерживается, т.к. мне кажется текущая цена это вообще первое и основное, что нужно получать...

П.С. Спасибо за все Ваши труды!!!

**Comment by cia76** [comment]
Добрый день! Можно воспользоваться функцией get_day_candles с датой окончания, например, завтрашней. Тогда Вам придет набор свечек с незавершенной текущей сессией. Цена закрытия и будет последней ценой сделки.
