### ISSUE TITLE
Теряется подписка на заявки и сделки

### ISSUE THREAD

**Issue by publine2** [cia76/FinamPy#7]
Посмотрите пожалуйста вопрос, опубликовал тут https://github.com/FinamWeb/trade-api-docs/discussions/51
Вообщим я уже 20 раз пожалел что сязался с этой убогой поделкой по имени finam api... Думаю бросить это все и сделать все заново через quick коннектор.

**Comment by cia76** [comment]
Т.к. я нахожусь на той же стороне, что и Вы, то скажу, что у каждого брокера свои странности. Например, для Алора я сделал коннектор пару лет назад. Но новые идеи завели Алор туда, где были убраны из спецификации основные функции, на которые я опирался. Поэтому пришлось садиться и полностью переписывать код. Понятно, что от этого никто не застрахован.

Что касается некачественного кода. Для того я и нужен, чтобы напрямую взаимодействовать с ответственными людьми, которые разрабатывают эти сервисы. Обычно, такие пожелания формируют генеральные директора брокеров.

Согласен, что по Финаму сложилась очень странная ситуация. С одной стороны, есть разработчики. У них есть задачи и сроки сдачи кода. С другой - на мои запросы далеко не всегда есть ответы.

Что сделал. Связался с Финамом. Думаю, что основную часть вопросов решим внутри их сообщества. Но вот баги (вы нашли только один из них), будем описывать и отправлять в Финам окольными путями.

**Comment by publine2** [comment]
...вообщим мне просто не повезло - я стал классической жертвой пропаганды всего самого лучшего, которая у нас в стране на каждом углу. ...надо просто научиться делить на 10 все что я читаю и слышу на русском....

если будете "окольными путями" отправлять баги в финам - передайте им что у них при работе только по REST api не возможно как либо определить реальную цену выполненой сделки, потому как при запросе ордеров там везде фигурирует указанная пользователем цена при отправке ордера. я уже писал им что было бы неплохо при  получении ордером статуса matched писать там уже реальную среднюю цену исполнения ордера. ..ну либо реализовать возможность запроса сделок через REST.

**Comment by cia76** [comment]
Постараюсь ответить по делу. Без эмоций. Не разглашая корпоративные секреты.

Изначально Финам хотел сделать API на REST. В принципе, стандартный способ, ничего особенного. Разработка базируется на TRANSAQ. Т.е. решение должно учитывать уже имеющуюся систему. Эта система, мягко говоря, не новая. Значит, возможны различные коллизии. Что и произошло. Я тогда уже работал с Алором. Предложил посмотреть на websockets. В Финаме выбрали gRPC.

Далее, было несколько спринтов. В конце прошлого мая выдали неплохой задел. Были планы на следующие месяцы. Но потом что-то изменилось. Понятно, что это - внутреннее дело Финама, но я бы хотел, чтобы мы, трейдеры, не стали заложниками их внутренней кухни.

На данный момент я больше всего в теме API Финама, не являясь ни их сотрудником, ни имея прямой доступ к разработчикам. Те наработки/решения, что сделал с ребятами в своем проекте "Финансовая Лаборатория" используем для автоторговли. Надеюсь, что скоро в Финаме дела устаканятся, и они "допилят" свой API.

**Comment by publine2** [comment]
Конечно websockets был бы лучше поскольку он стабильно держит соединение в отличии от gRPC. 
tradingview работает на websockets - несколько лет уже им пользуюсь, только положительные отзывы.

**Comment by publine2** [comment]
Вообщим на данный момент все работает примерно так(работает нон-стоп уже неделю): вне зависимости от того есть активная подписка или нет, в любом случае перед тем как отправлять ордер выполняем отписку, ждем 5 секунд, выполняем подписку с обязательным контролем ответа через on_response, ждем 5 сек., отправляем ордер. Ожидание ответа on_response происходит в течении 10 секунд от момента подписки. Эта процедура выполняется перед КАЖДЫМ новым ордером, иначе подписка не работает. Бывает так что процедуру отписки-подписки приходится выполнять несколько раз подряд с перерывом в минуту, так как не приходит ответ в on_response. Удивительно что при этом keep_alive отрабатывает отлично но при этом ни на что не влияет, т.е. он по факту нафиг не нужен. Соединение, прямое, без каких либо посредников(прокси, VPN), провайдер ростелеком, канал 100 мегабит витая пара, практически всегда не загружен(средняя загрузка ниже 20%), операционка Linux, фаервол полностью отключен. Отдельно параллельно автоматически контролировалась доступность простейших общедоступных сайтов(для того чтоб убедиться что проблемы не со связью), никаких перебоев не обнаружено.
