### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by Vsevosemnog** [cia76/FinamPy#8]
Здравствуйте, скачал проект, сделал venv, установил пакеты из requirements.txt

```
python3 -m venv .venv
source .venv/bin/activate
pip3 install -r requirements.txt
```

Заполнил Config.py.
Сделал тестовый файлик, чтобы со своим токеном подтянуть портфель.

```
from FinamPy import FinamPy

if __name__ =="__main__":
    fp_provider = FinamPy() 

    portfolio = fp_provider.get_portfolio('<ЗДЕСЬ ID счета>')
    for money in portfolio.money:
        print(f'  - {round(money.balance, 2)} {money.currency}')
```

При запуске python3 main.py вылетает следующая ошибка:
python3 main.py
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/usermain/Documents/Algo-trade/FinamPy/FinamPy.py", line 14, in <module>
    from .proto.tradeapi.v1.events_pb2 import KeepAliveRequest  # Запрос поддержания активности
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: attempted relative import with no known parent package
```

Подскажите, пожалуйста, что-то не так делаю при взаимодействии с кодом проекта? Интерпретатор словно не видит модули
Проблема и на Ubuntu, и на Windows
Аналогичная проблема при попытке использовать примеры из директории Examples
python3 Examples/Account.py

Как вы запускаете код примеров?

Python 3.11.6

**Comment by cia76** [comment]
Приветствую!

Надо скопировать из проекта папки grpc и proto чтобы было куда обращаться.

Также посмотрите, есть ли доступ к ним по относительным путям .proto и .grpc

Перед тем, как запустить свой скрипт настоятельно рекомендую по порядку запустить все скрипты из Examples. Я их делал так, чтобы закрыть как можно больше основных торговых функций.

**Comment by Vsevosemnog** [comment]
> Приветствую!
> 
> Надо скопировать из проекта папки grpc и proto чтобы было куда обращаться.
> 
> Также посмотрите, есть ли доступ к ним по относительным путям .proto и .grpc
> 
> Перед тем, как запустить свой скрипт настоятельно рекомендую по порядку запустить все скрипты из Examples. Я их делал так, чтобы закрыть как можно больше основных торговых функций.

Да, конечно, proto, grpc присутствуют, потому что я сделал git clone всего проекта FinamPy и запускаю скрипт в нем. 
![image](https://github.com/cia76/FinamPy/assets/37411749/f1700650-8470-4b19-a6f1-2b9d4699abbd)

К сожалению, не работает. Не работают также примеры из Examples. Видимо, проблема заключается в том, что я запускаю свой или скрипт примера и не выходит увидеть и подгрузить нормально модули библиотеки в том числе из-за относительного импортирования. Хорошо, буду разбираться

Если у вас есть launch.json файл для правильного запуска кода, поделитесь, пожалуйста?
Есть ли консольная команда для запуска скрипта-примера, если да, поделитесь, пожалуйста?

**Comment by cia76** [comment]
Попробовал запустить в VSCode. Все относительные пути видит. Дополнительных настроек не делал. Думаю, что Вы правы. Вопрос в относительном импорте. Надо понять, от какой папки у Вас идет отсчет.

У одного трейдера был подобный вопрос. Решился вот так:

from FinamPy.FinamPy.proto.tradeapi.v1.events_pb2 import KeepAliveRequest  # Запрос поддержания активности

Но лучше разберитесь с путями.

**Comment by Vsevosemnog** [comment]
Спасибо за помощь и совет!
