### ISSUE TITLE
Ошибка Security not found

### ISSUE THREAD

**Issue by publine2** [cia76/FinamPy#9]
../FinamPy/Examples/Bars.py

если укажем:
    security_board = 'FUT'  # Акции ММВБ
    security_codes = ('SRM4',)  # Для тестов

то получим:
FinamPy - ERROR - Ошибка Security FUT:SRM4 not found при вызове функции /grpc.tradeapi.v1.Candles/GetDayCandles с параметрами security_board: "FUT"
security_code: "SRM4"

по факту же все везде есть

**Comment by cia76** [comment]
Да, этот тикер есть. Ошибка на стороне Финама. Отправил в поддержку.
